#!/bin/bash 
#SBATCH --job-name=F2_CCSD
#SBATCH --output=log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mem=100GB
#SBATCH --qos=bartlett
#SBATCH --constraint=milan

ulimit -a
#
module purge 
module load conda; conda activate pyscfDev2; module load intel/2020.0.166
#export OMP_NUM_THREADS=8
python ccsdt.py > out.out

#cat ZMAT >> aces2.out
#mv aces2.out $job.out
#cp $job.out $TESTROOT 
#rm -r $WORKDIR

